name: seismic

services:
  directus:
    extends:
      file: apps/directus/docker-compose.yml
      service: directus

  directus-db:
    extends:
      file: apps/directus/docker-compose.yml
      service: directus-db
    networks:
      - seismic-network
  # prometheus:
  #   extends:
  #     file: apps/prometheus/docker-compose.yml
  #     service: prometheus

  # grafana:
  #   extends:
  #     file: apps/grafana/docker-compose.yml
  #     service: grafana

networks:
  seismic-network:
    driver: bridge
  monitoring:
    name: monitoring
    driver: bridge

# volumes:
#   prometheus_data:
#   grafana_data: