name: turbo-25

services:
  redis:
    container_name: turbo-25-redis
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - turbo-25-network
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_USER=${REDIS_USER:-default}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-secret123}

volumes:
  redis-data:

networks:
  turbo-25-network:
    driver: bridge
