global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'swarm'
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'sentry'
    static_configs:
      - targets: ['sentry-web:9000']
    metrics_path: '/metrics'
    scrape_timeout: 10s