[install]

command = "pnpm install"
[build]
builder = "nixpacks"
buildCommand = "pnpm run build:backend-api"

[deploy]
startCommand = "cd apps/api && pnpm run start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10