version: '3'

services:
  app:
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ${VOLUME_SOURCE}:${VOLUME_DESTINATION}
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - app-network
    restart: unless-stopped

volumes:
  app-data:

networks:
  app-network:
    external: true
