version: '3'

services:
  sentry-postgres:
    image: postgres:15
    container_name: sentry-postgres
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: ${SENTRY_DB_PASSWORD}
      POSTGRES_DB: sentry
    volumes:
      - sentry-postgres:/var/lib/postgresql/data
    networks:
      - sentry-network

  sentry-redis:
    image: redis:6.2
    container_name: sentry-redis
    volumes:
      - sentry-redis:/data
    networks:
      - sentry-network

  sentry-web:
    image: getsentry/sentry:latest
    container_name: sentry-web
    depends_on:
      - sentry-redis
      - sentry-postgres
    ports:
      - "9000:9000"
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: sentry-postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: ${SENTRY_DB_PASSWORD}
      SENTRY_REDIS_HOST: sentry-redis
    volumes:
      - sentry-data:/var/lib/sentry/files
    networks:
      - sentry-network
    command: ["run", "web"]

  sentry-worker:
    image: getsentry/sentry:latest
    container_name: sentry-worker
    depends_on:
      - sentry-redis
      - sentry-postgres
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: sentry-postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: ${SENTRY_DB_PASSWORD}
      SENTRY_REDIS_HOST: sentry-redis
    volumes:
      - sentry-data:/var/lib/sentry/files
    networks:
      - sentry-network
    command: ["run", "worker"]

  sentry-cron:
    image: getsentry/sentry:latest
    container_name: sentry-cron
    depends_on:
      - sentry-redis
      - sentry-postgres
    environment:
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_POSTGRES_HOST: sentry-postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: ${SENTRY_DB_PASSWORD}
      SENTRY_REDIS_HOST: sentry-redis
    volumes:
      - sentry-data:/var/lib/sentry/files
    networks:
      - sentry-network
    command: ["run", "cron"]

volumes:
  sentry-postgres:
  sentry-redis:
  sentry-data:

networks:
  sentry-network:
    name: sentry-network 